# These are supported funding model platforms
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

custom:
  - https://buy.stripe.com/14AcN5gBJ6rRfm07Kz2cg0c
